### ISSUE TITLE
Webstore layout bug

### ISSUE THREAD

**Issue by loweryB85** [KrisB88/Textile#38]
This may not be something worth fixing yet as there are other things that need attention first but just so it is known - if the window is not wide enough for the store menu to be displayed on the left hand side of the page as intended, it floats behind all of the items in the store as you scroll down the page.

Upon further inspection it seems that under this condition, a number of things don't display properly 

![layout_bug](https://cloud.githubusercontent.com/assets/8731258/5042118/2fd07c7e-6b95-11e4-9a46-784fbd0eee07.jpg)

**Comment by hrw2i** [comment]
What exactly is the issue here?

**Comment by devgr** [comment]
Looks like the problem is that the layout doesn't look right when the shopping cart is open and the browser window is narrow?

**Comment by hrw2i** [comment]
Got the resizing issues fixed (shopping cart columns collapsing when window is narrow, sidebar shop menu persisting upon scroll under items)
